### ISSUE TITLE
DDP 설정 시 Modality값을 -로 설정하였을 경우 아무런 액션이 없습니다.

### ISSUE THREAD

**Issue by JungyunByun** [HealthHub-Project/HPACS#102]
**Modality: -**
DDP 설정 시 위와 같이 선택할 경우 모든(ALL) Modality에 대해 DDP가 설정이 될 것으로 생각하였습니다.
하지만, -를 선택하는 것이 모든(ALL) Modality를 뜻하는 것이 아니라 -라는 값을 가진 Modality에 대해 적용이 되는 것 같습니다. 
DDP 설정 창을 띄웠을 때 디폴트로 Modality가 -로 선택되어 있기 때문에 자연스럽게 -값을 ALL이라고 착각하였습니다.
-> 디폴트로 -가 아닌 다른 값이 설정되면 사용자에게 혼란을 덜 줄 수 있을 거라 생각됩니다. 
-> 더불어, Modality 뿐 아니라 Bodypart 리스트 내에도 (), 1(), 2(), Default 값과 같은 의미 전달이 명확하지 않은 값들이 있는데 정리가 필요할 것으로 생각됩니다.

**Comment by mjkim112** [comment]
'-'(하이픈) 값을 가진 Modality에 대해 적용
>> modality의 hie_unknown을 worklist에서 '-'(하이픈)으로 viewing
>> modality의 '-'(하이픈)을 worklist에서 '='로 viewing

**Comment by mjkim112** [comment]
radrex코드로 변경중
