### ISSUE TITLE
Report ver 1.0

### ISSUE THREAD

**Issue by JUNGJOOHYUK** [HealthHub-Project/HPACS#112]
[원장님 UI/UX 설계 문서](https://drive.google.com/drive/u/0/folders/1gZj0Xujeh1tgYcIj0TsLu9QAZ-NeGiq1)

### WORK
- 레이아웃 생성 (기존 레이아웃 변경 및 Expand 기능)
- (components) reading template
    - **new reading template (radrex)**
    - setting reading templte
- (components) thumbnail
    - setting
- (components) report image
- (components) clinical info
- (components) report
    - setting
    - consult to
    - mark CVR
- (components) old film 판독문
- 기타
    - SR
    - Dictation
    - Transcription

**Comment by mjkim112** [comment]
**[제외항목]**
#(components) report
* mark CVR
#기타
* SR
* Dictation
* Transcription
