### ISSUE TITLE
HPACS 직무교육(19.2.11) 요청사항

### ISSUE THREAD

**Issue by JUNGJOOHYUK** [HealthHub-Project/HPACS#116]
- 판독문 출력여부 표시 : 판독문을 출력할 경우, 출력 여부를 화면에 표시

- 판독의 변경 : 판독문에 최종 판독 책임자자가 기재되는데, 해당 판독 책임자를 변경할 수 있는 기능

- 판독완료된 이후, 수정사항이 생겨 판독문이 변경되었을 경우, 이를 인지할 수 있도록 표시

**Comment by eunbeegracekim** [comment]
권한이 없는데 코멘트 달리나?

**Comment by HealthHub-Project** [comment]
이메일이 오긴했어요!!

2020년 7월 8일 (수) 오후 6:08, eunbeegracekim <notifications@github.com>님이 작성:
