### ISSUE TITLE
컬럼명 변경

### ISSUE THREAD

**Issue by JUNGJOOHYUK** [HealthHub-Project/HPACS#2]

**Comment by racahn** [comment]
컬럼명 변경 요청
1. 모든 팝업명에 풍선도움말 붙일 것

2. RS: Reading State, 판독의 상태를 나타내는 컬럼의 state machine
wait: (판독대기중)
consulted: 다른 radiologist가 나에게 컨설트를 함.
consulting: 내가 다른 radiologist에게 컨설트함
consult replied: 컨설트가 대답이 옴 컨설팅 관련 세개의 status는 맨 윗줄로 올라가 있어야 함.
dictated (판독 녹음됨)
transcribed (판독 전사됨)
confirmed (판독확인됨)
preliminary: 코사인이 붙은 경우 senior doctor가 confirm을 안한 경우, 판독은 publishing을 하고 상태는 preliminary, 코사인을 해야할 의사의 환자리스트 맨 위에 표시
viewing (다른 사람이 보고 있는 중)
save: 판독하다가 딴일할 때 잠시 저장, suspend한 radiologist의 이름이 나타날 수 있도록 함.
excepted: echo, 내시경, pathology등 PACS상에서 판독을 안하는 경우는 excepted 로 표시
addendum (판독에 새로운 내용이 추가되었거나 변경되었을때)


4. CHospital --> EHospital (Hospital of Examination, 검사한 병원)으로 변경, 다이콤 태그 내에 검사 병원을 표시, 검사병원 표시, outside film인 경우는 검사한 병원 표시, 본원이면 본원이름 표시

5. CDept --> Dept
6. CDoctor --> RDoctor (referring doctor)
7. Operator --> Tech (Radiology technician)

신설
1. SS (Study State) 신설,  study 상태, MPPS의 state, 태그 네임은 
ordered: 외래에서 오더되어 work list server에 queing 됨
scheduled: RIS에서 pickup되어 검사 scheduling이 확정됨, 예측 대기시간 표시
in progress (imaging): 촬영중
completed :촬영완료
discontinued: RIS 또는 OCS에서 오더 취소, 실제 표시는 환자리스트에서 사라짐으로 표현, D/C 리스트는 따로 제공
2. TS (Tele status): 원격판독 상태
sending: 사진을 보내는 중
sent: 전송완료
fail: 전송실패
receiving: 받는중
received: 다 받았음
3. Section: modality와 body part 를 기반으로 section을 나눔, ex) NR, HN, breast, chest, abdomen, GU, angio.....


4. wards: 입원환자의 경우 병동, 외래환자의 경우 외래 표시, 외래 특수클리닉 등을 표시하여야 함
5. Exam Room: 촬영실 정보 (ex. US1, US2, DX1, DX2, MR1, MR2, CT1, CT2)
6. Storing date: PACS에 check in 된 일시
7. paramedicMemo: 검사중 생긴 event에 대해 검사자가 쓴 메모
8. Report: 판독이 완료된 케이스에서 판독문내의 conclusion을 표시
9. LOINC : 맵핑된 LOINC 코드

**Comment by mjkim112** [comment]
- 컬럼명 변경(CHospital -> EHospital, CDept -> Dept, CDoctor->RDoctor, Operator->Tech)
- 컬럼명 추가(No, Verify)
