### ISSUE TITLE
HResizer 기능 축소 및 보완

### ISSUE THREAD

**Issue by mjkim112** [HealthHub-Project/HPACS#81]
- 필름박스 모니터에 맞게 자동 크기조절 기능 삭제
 - 모니터의 위치, OS에 상관없이 필름박스 모니터에 맞게 사용자가 수동으로 위치, 크기를 지정했을 경우 라벨을 지정하여 서버에 저장
 - 옵션창에서 default 라벨값을 선택하면, 그 다음부터 해당 위치에 필름박스가 위치함.
 - 옵션창에서 CRUD 기능 제공

**Comment by zzangbohyun** [comment]
10.19 요청 세팅된 배율에 관계없이 같은 크기, 위치에 보여줄수 있도록 수정 
window.devicePixelRatio : 현제 화면의 배율 값.(ex 100% : 1, 125% : 1.25)
