### ISSUE TITLE
필름박스 어노테이션(with text) 오류사항 수정

### ISSUE THREAD

**Issue by JUNGJOOHYUK** [HealthHub-Project/HPACS#89]
실제 길이가 표시되도록 수정

**Comment by mjkim112** [comment]
**# Ruler 요구사항 추가**

1) 10cm -> 5cm로 수정

2) cm 출력

3) 0.5일때 눈금 추가

4) 눈금 길이 짧게 수정 ( 완료 )

5) Ruler 색 흰색으로 수정

6) text 위치가 다른곳에 출력되는 것 확인( DDP 1*3개로 지정되어있을때 text 위치 )

7) 소숫점자릿수 1개로 수정 ( 완료 )

8) 자는 우측에 하나만 출력하게끔 수정 ( 현재 좌측, 하단 2개 )

**Comment by mjkim112** [comment]
요구사항 추가건은 다음 버전때 수정
